language: node_js
node_js:
  - lts/*
git:
  depth: 3
cache:
  - pip
  - npm
before_install:
- openssl aes-256-cbc -K $encrypted_d4a09416a845_key -iv $encrypted_d4a09416a845_iv
  -in .staging.key.json.enc -out .staging.key.json -d
install:
  - pip install grow==0.7.4 --user
  - grow --version
  - npm ci

jobs:
  include:
    - stage: build
      script:
        - npm run build:staging -- --locales en,fr,ar --playground --boilerplate
    - stage: build
      script:
        - npm run build:staging -- --locales es,it,id
    - stage: build
      script:
        - npm run build:staging -- --locales ja,ko,pt_BR
    - stage: build
      script:
        - npm run build:staging -- --locales ru,tr,zh_CN
    - stage: deploy
      install:
        - pip install gsutil --user

deploy:
  provider: gae
  keyfile: ".staging.key.json"
  project: amp-dev-staging
  skip_cleanup: true
  on:
    branch: future
