# This file will be modified during build time if project is built via CI
# inspect it during runtime by visiting /who-am-i
number: TRAVIS_BUILD_NUMBER
timestamp: NOW
commit:
  sha: TRAVIS_COMMIT
  message: TRAVIS_COMMIT_MESSAGE
