# Use via: go.amp.dev/samples
/samples: /documentation/examples/
/camp-code: https://github.com/ampproject/samples/tree/master/amp-camp
/docs: /documentation/
/learn: /documentation/courses/
/websites: /about/websites
/stories: /about/stories
/stories-best-practices: /documentation/guides-and-tutorials/develop/amp_story_best_practices
/ads: /about/ads
/email: /about/email
/vision-mission: /about/mission-and-vision
/governance: /community/governance
/shopify-apps: https://blog.amp.dev/2019/04/15/shopify-apps-make-amp-easy-and-effective-for-ecommerce
/publishing-checklist: https://amp.dev/documentation/guides-and-tutorials/optimize-and-measure/publishing_checklist.html
/io-email: /documentation/examples/interactivity-dynamic-content/conference_survey_email/
